export const data = [
  {
    id: 1,
    itemName: "UCW",
    uom: "Nos",
    totalQuantity: 2723,
    targetDate: new Date("21-07-2025".split("-").reverse().join("-")),
    supply: 2200,
    yetToSupply: 523,
    installation: 1800,
    yetToInstall: 923,
    percentSupply: null,
    percentInstallation: null,
    remarks: "On track",
  },
  {
    id: 2,
    itemName: "LCB",
    uom: "Nos",
    totalQuantity: 1500,
    targetDate: new Date("22-07-2025".split("-").reverse().join("-")),
    supply: 1200,
    yetToSupply: 300,
    installation: 900,
    yetToInstall: 600,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Delay expected",
  },
  {
    id: 3,
    itemName: "MCU",
    uom: "Nos",
    totalQuantity: 800,
    targetDate: new Date("23-07-2025".split("-").reverse().join("-")),
    supply: 800,
    yetToSupply: 0,
    installation: 650,
    yetToInstall: 150,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Supply complete",
  },
  {
    id: 4,
    itemName: "PSU",
    uom: "Nos",
    totalQuantity: 1200,
    targetDate: new Date("24-07-2025".split("-").reverse().join("-")),
    supply: 900,
    yetToSupply: 300,
    installation: 400,
    yetToInstall: 300,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Pending inspection",
  },
  {
    id: 5,
    itemName: "HMI",
    uom: "Nos",
    totalQuantity: 500,
    targetDate: new Date("25-07-2025".split("-").reverse().join("-")),
    supply: 500,
    yetToSupply: 0,
    installation: 500,
    yetToInstall: 0,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Fully installed",
  },
  {
    id: 6,
    itemName: "PLC",
    uom: "Nos",
    totalQuantity: 1800,
    targetDate: new Date("26-07-2025".split("-").reverse().join("-")),
    supply: 1500,
    yetToSupply: 300,
    installation: 1200,
    yetToInstall: 600,
    percentSupply: null,
    percentInstallation: null,
    remarks: "In progress",
  },
  {
    id: 7,
    itemName: "VFD",
    uom: "Nos",
    totalQuantity: 950,
    targetDate: new Date("27-07-2025".split("-").reverse().join("-")),
    supply: 600,
    yetToSupply: 350,
    installation: 300,
    yetToInstall: 60,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Awaiting parts",
  },
  {
    id: 8,
    itemName: "UPS",
    uom: "Nos",
    totalQuantity: 700,
    targetDate: new Date("28-07-2025".split("-").reverse().join("-")),
    supply: 700,
    yetToSupply: 0,
    installation: 200,
    yetToInstall: 50,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Testing phase",
  },
  {
    id: 9,
    itemName: "RPP",
    uom: "Nos",
    totalQuantity: 2200,
    targetDate: new Date("29-07-2025".split("-").reverse().join("-")),
    supply: 1800,
    yetToSupply: 400,
    installation: 1500,
    yetToInstall: 700,
    percentSupply: null,
    percentInstallation: null,
    remarks: "On schedule",
  },
  {
    id: 10,
    itemName: "CBL",
    uom: "Meters",
    totalQuantity: 5000,
    targetDate: new Date("30-07-2025".split("-").reverse().join("-")),
    supply: 3500,
    yetToSupply: 1500,
    installation: 2500,
    yetToInstall: 2500,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Partial delivery",
  },
  {
    id: 11,
    itemName: "SWG",
    uom: "Nos",
    totalQuantity: 300,
    targetDate: new Date("31-07-2025".split("-").reverse().join("-")),
    supply: 300,
    yetToSupply: 0,
    installation: 200,
    yetToInstall: 100,
    percentSupply: null,
    percentInstallation: null,
    remarks: "New batch",
  },
  {
    id: 12,
    itemName: "MCC",
    uom: "Nos",
    totalQuantity: 450,
    targetDate: new Date("01-08-2025".split("-").reverse().join("-")),
    supply: 300,
    yetToSupply: 150,
    installation: 1500,
    yetToInstall: 300,
    percentSupply: null,
    percentInstallation: null,
    remarks: "Pending approval",
  },
];
